### ISSUE TITLE
Upgrade Windows build to Visual Studio 2017

### ISSUE THREAD

**Issue by UniversalBinary** [libbitcoin/libbitcoin#810] opened 2017-10-18 00:21 UTC
The Visual Studio project files still require Visual Studio 2013 to build, and won't build under later editions. Is it possible to update the project to Visual Studio 2017, which we are now up to. Also, the dependencies (Boost, etc) are available in VCPKG, which would be preferable to NuGet.

**Comment by evoskuil** [comment] 2017-10-19 00:56
There are plans to move all VS project files into libbitcoin-build source generation. This would mirror the non-VS process, which is fully generated. Would would not "update" to any single version, as that creates a break for all dependent projects using the previous version. So the generation would generate all versions starting at 2013. Until this is implemented we will be on 2013. I'm not sure when that will be.

VCPKG would limit flexibility in boost and zeromq version selection, and does not include all of the stack's dependencies (see optional bc and bx dependencies), and presents an inconsistency for downlevel version support, so wouldn't present as a compelling advantage.

**Comment by evoskuil** [comment] 2017-10-22 08:29
This is a duplicate of https://github.com/libbitcoin/libbitcoin-build/issues/54

**Closed by evoskuil** 2017-10-22 08:29 UTC
Labels: build
