### ISSUE TITLE
[msvc] test failure: electrum__create_mnemonic__es_dictionary_prefix__valid

### ISSUE THREAD

**Issue by ldz1** [libbitcoin/libbitcoin#1029] opened 2018-09-08 10:40 UTC
Hello,

I am trying to run the libbitcoin tests from master on Windows 10 64 bit. The build was created through the build.. .bat. I am running the libbitcoin-test.exe through the cmd. The cmd code page was set to 65001 (chcp 65001). The test run fails on 

test\wallet\electrum.cpp (90) : Entering test case "electrum__create_mnemonic__es_dictionary_prefix__valid" 

with following error: https://s8.postimg.cc/duppahtg5/libbitcoin_Test_Error.png.

The cmd font is Lucida Console. All builds (64/32 debug/release) generate the reported issue. 

Wat is the right way to run the tests on Windows? 

Thank you in advanced.

**Comment by evoskuil** [comment] 2018-09-08 16:29
This works with tests invoked in the post-build step. Not sure what would be the difference.

**Comment by evoskuil** [comment] 2018-09-08 22:45
It also works when invoked as a command.

**Comment by evoskuil** [comment] 2018-09-08 23:18
There is a VS-only test-only issue here, and the test failure is not propagated when `--report_level=no` is set due to the set_utf8_stdout statement.

**Comment by thecodefactory** [comment] 2018-09-09 02:48
@evoskuil I can look into this more, but since I can't reproduce it, it may be difficult.  I vaguely recall this being a windows error we discussed where in fact the windows result is just not correct (it skips the correct answer for some reason and keeps iterating when it shouldn't).  I thought you had uncovered and resolved it though.

**Comment by evoskuil** [comment] 2018-09-09 09:33
I don't recall resolving the issue. If you review the diff for the related PR you can see that I removed two lines from the test. The first line was causing the scram output to fail when the tests are executed in VS. Yet I confirmed the test was still failing, and it was emitting the failure when the the test exe was run in a different console. The PR removes the `set_utf8_stdout();`, which is incorrect, causing the error to show. Incidentally this may have resulted in suppression of errors in all subsequent tests, since it has a persistent side effect.

**Comment by thecodefactory** [comment] 2018-09-09 13:33
> I don't know what is the cause of the failure, but it remains unresolved. Given that the failure affects the only Unicode test, it may pertain to Unicode, and the failure only affects VC++ builds.

The electrum mnemonic tests are sparse (https://github.com/spesmilo/electrum/blob/master/electrum/tests/test_mnemonic.py) and don't have any good vectors that we can compare against (except that first one, which we already do).

I just tried loading up the wallet, and I can't seem to find an option to get a mnemonic in a non-english language (if anyone knows, please let me know).  Yet their code does include the wordlists and **I think I found the source of the issue**:

https://github.com/spesmilo/electrum/blob/master/electrum/mnemonic.py#L78

The normalization process we're using is incomplete and I'm not sure how I overlooked that before, given the substantial differences.

If there are any electrum/python people out there, using the electrum code to generate a set of mnemonics in languages other than english along with the seeds (hex) and the entropy used for mnemonic creation would be very helpful for testing against.

I'll have to try to do that myself in the meantime in order to test that the normalization process is complete.

**Comment by evoskuil** [comment] 2018-09-09 17:03
Probably worth a notice to the mailing list to notify anyone who may be using the non-en wordlists in a wallet. Also, I'm wondering how the test is passing on linux/osx.

**Comment by thecodefactory** [comment] 2018-09-09 19:04
> Probably worth a notice to the mailing list to notify anyone who may be using the non-en wordlists in a wallet. Also, I'm wondering how the test is passing on linux/osx.

Sure, will send something soon.

As for the test passing, it just means that GNU/Linux and OS X agree on the output of `is_new_seed` (https://github.com/libbitcoin/libbitcoin/blob/master/src/wallet/electrum.cpp#L118) and Windows does not.

**Comment by evoskuil** [comment] 2018-09-09 20:13
This implies that `to_normal_nfkd_form` is inconsistent, which is a big deal. We haven't seen any issue with this in other contexts.

**Comment by SomberNight** [comment] 2018-09-10 00:09
> If there are any electrum/python people out there, using the electrum code to generate a set of mnemonics in languages other than english along with the seeds (hex) and the entropy used for mnemonic creation would be very helpful for testing against.

I've added a few more tests in https://github.com/spesmilo/electrum/commit/999ae1f7134016814a4337542cd32941ff42132c

**Comment by thecodefactory** [comment] 2018-09-10 00:56
@SomberNight Great, thanks -- that will help quite a bit!

**Comment by evoskuil** [comment] 2018-10-16 21:57
status?

**Comment by ldz1** [comment] 2018-11-04 14:54
There is something wrong at least with the HMACSHA512 on Windows (VS, libbitcoin) related to the accents.

Electrum (Linux):
**input**
data (as bytes): "fat pride clean tuition tag crumble proof coral solution design detect twin"
key (as bytes): "Seed version"
**output** 
(hex): 60502304f462f1e4bedcae98461ae5369ac8c303a55b785e3ec6702bb391960ea4786f5cee11c5db7b53c9120b06d903e74dffd73bc6271522409eb1cace333c

The same input/output can be generated with VS (libbitcoin) and the Microsoft .NET HMACSHA512 Class (e.g. C#). https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.hmacsha512?redirectedfrom=MSDN&view=netframework-4.7.2

Electrum (Linux):
**input**
data (as bytes): "explicar papá capitán tomar sufrir coco paseo charla ruleta cubo cuerda toro"
key (as bytes): "Seed version"
**output** 
(hex): ead31fe112f9e49f50064599bcda1765ad1aec37e0e798f5d9eef218897a33a0b43b92e40cd65e68d18a2e96c5624add3b4a922488b8d1242580263eb0744d05

The same input/output cane be generated with Microsoft .NET HMACSHA512 Class but the VS (libbitcoin) output is different.

Apart from the HMAC problem, the electrum normalizing implementation is a little different. Electrum removes accents (libbitcoin doesn't), but I think at first we need to understand why hmac_sha512.c behaves different on windows.

**Comment by evoskuil** [comment] 2018-11-04 15:51
I suspect your test cases are not properly handling Unicode conversion.

**Comment by ldz1** [comment] 2018-11-04 21:42
@evoskuil: Just like you said on slack, probably the inputs were not the same. Please ignore my above post first.

**Comment by ldz1** [comment] 2018-11-04 22:54
á = 61 cc 81
á = c3 a1

The nkfd form: 61 cc 81.

Electrum / .NET Framework normalization returns "61 cc 81". Libbitcoin normalizes to "c3 a1" instead of "61 cc 81". Very strange.

**Comment by evoskuil** [comment] 2018-11-04 23:10
Are the inputs to UTF8 normalization the same bytes? It doesn’t appear so.

**Comment by ldz1** [comment] 2018-11-04 23:54
Electrum: c1 a1 (nkfd)-> 61 cc 81.
.NET: c1 a1 (nkfd)-> 61 cc 81.
Libbitcoin (Windows): c1 a1 (nkfd)-> c1 a1.

Electrum: 61 cc 81 -> 61 cc 81
Framework: 61 cc 81 -> 61 cc 81

**Comment by evoskuil** [comment] 2018-11-05 01:36
This test case passes:
```cpp
BOOST_AUTO_TEST_CASE(unicode__to_normal_nfkd_form__61cc81__c3a1)
{
   const std::string literal_c3a1 = "á";

   // This is pasted from the the BIP39 encoding:
   //// github.com/bitcoin/bips/blob/master/bip-0039/spanish.txt#L93
   const std::string literal_61cc81 = "á";

   const std::string string_c3a1 = "\xc3\xa1";
   const std::string string_61cc81 = "\x61\xcc\x81";
   BOOST_REQUIRE_EQUAL(string_c3a1, literal_c3a1);
   BOOST_REQUIRE_EQUAL(string_61cc81, literal_61cc81);

   const auto normalized_c3a1 = to_normal_nfkd_form(string_61cc81);
   BOOST_REQUIRE_EQUAL(normalized_c3a1.c_str(), string_c3a1);

   const auto unchanged_c3a1 = to_normal_nfkd_form(string_c3a1);
   BOOST_REQUIRE_EQUAL(unchanged_c3a1.c_str(), string_c3a1);
}
```

I've added it to unicode.cpp tests and will pull to master.

**Comment by ldz1** [comment] 2018-11-06 00:03
There is no ICU backend on Windows inside https://github.com/libbitcoin/libbitcoin/blob/master/src/unicode/unicode.cpp#L92
There are winapi and std backend on Windows and winapi seems to be the default one. 
( https://www.boost.org/doc/libs/1_67_0/libs/locale/doc/html/using_localization_backends.html )

I am not sure, but I believe the ICU beckend is necessary to run the normalize function correctly. I think the ICU beckend is missing because the boost locale is provided without ICU dependency. There is a possibility to build boost locale with ICU but actually no idea how to integrate this with libbitcoin builds. 
https://www.boost.org/doc/libs/1_52_0/libs/locale/doc/html/building_boost_locale.html

**Comment by evoskuil** [comment] 2018-11-06 00:06
@pmienk can prob help out with integration.

**Comment by thecodefactory** [comment] 2018-11-13 17:45
@SomberNight Thanks again for adding the additional tests!  I've almost got them all worked out by now, but wanted to ask if there are spanish tests, or if you might be able to readily add those.  We seem to have some spanish test discrepancies and the more sanity checking, the better.

**Comment by SomberNight** [comment] 2018-11-14 18:01
Sure. I've added Spanish tests in https://github.com/spesmilo/electrum/commit/f767d41409ad20e60bf535fb78468f276679b6fb

**Comment by thecodefactory** [comment] 2018-11-14 18:15
> Sure. I've added Spanish tests in spesmilo/electrum@f767d41

@SomberNight Perfect, thanks!

**Comment by thecodefactory** [comment] 2018-11-15 02:49
@SomberNight Tests are not merged, but are incorporated here (within PR https://github.com/libbitcoin/libbitcoin/pull/1073):

https://github.com/libbitcoin/libbitcoin/blob/2585536dafd8877518c07f34e73669a2c6aeba67/test/wallet/electrum.cpp

Thanks again!  I couldn't have gotten this done properly without the reference as assistance.

**Comment by evoskuil** [comment] 2018-12-10 00:14
Disabled WITH_ICU in VS builds.

**Closed** 2018-12-10 00:14 UTC
Labels: bug

**Comment by ldz1** [comment] 2018-12-13 17:06
@sergey-shandar would it be possible for you to prepare boost locale with icu as a nuget package (vs2013, 2015, 2017), please?

**Comment by ldz1** [comment] 2018-12-16 22:03
My experience in this topic is low. Because of that I will not try to convince anyone. I only believe the package must be built in a specific way (like the Linux case) to use the icu feature. 

From boost.org;
"Building Process"
"If you are using custom ICU build or you are using Microsoft Windows you need to provide a path to location of ICU library using -sICU_PATH option"

If I am right, the question is how the package was built so far. And I hope @sergey-shandar could give us more information. In other words, for example are you sure that the option "boost.locale.icu=off disable build of ICU backend even if ICU library exists" hasn't been set? I don't have any information about the build process.

**Comment by evoskuil** [comment] 2018-12-17 00:13
I don’t know, it’s a good question. Certainly the boost build should enable ICU if it’s always available. And it shouldn’t succeed on a call that requires ICU if it’s not linked, though that’s an entirely different issue.
