### ISSUE TITLE
VS 2017 Compiler Error C2001:newline in constant

### ISSUE THREAD

**Issue by houruixiang** [libbitcoin/libbitcoin#839] opened 2017-11-29 08:03 UTC
I'm using VS2017 to compile Engineering， I found: ..\libbitcoin\src\wallet\dictionary.cpp Compiler Error C2001:newline in constant .How should I fix this bug？？？

**Comment by evoskuil** [comment] 2017-11-29 13:13
It's not a bug (yet) because VS2017 is not yet supported. However I do expect this support very soon. Just guessing but it may be that VS is not treating the file as UTF8.

**Comment by evoskuil** [comment] 2017-11-30 07:43
This should be resolved by https://github.com/libbitcoin/libbitcoin-build/issues/114

**Closed by evoskuil** 2017-11-30 07:43 UTC
Labels: question

**Comment by houruixiang** [comment] 2017-11-30 14:12
Thank you.

发送自 Windows 10 版邮件应用

发件人: Eric Voskuil
发送时间: 2017年11月30日 15:43
收件人: libbitcoin/libbitcoin
抄送: houruixiang; Author
主题: Re: [libbitcoin/libbitcoin] VS 2017 Compiler Error C2001:newline inconstant (#839)

Closed #839.
