### ISSUE TITLE
Undefined symbol "_main" building with --disable-shared

### ISSUE THREAD

**Issue by JasonCoombs** [libbitcoin/libbitcoin#1007] opened 2018-08-12 00:57 UTC
This should be very simple to fix, as the main function is defined in BC_USE_LIBBITCOIN_MAIN but the reason that BC_USE_LIBBITCOIN_MAIN isn't being defined properly when --disable-shared is used doesn't immediately jump out at me.

Building on MacOS Version 10.13.5 (High Sierra) with --disable-shared

`$ ./install.sh CFLAGS="-Og -g" --disable-shared --prefix=/dir
`

Error: Undefined symbol "_main"

```
  CXXLD    test/libbitcoin-test
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
     (maybe you meant: __ZN21payment_address_tests71payment_address__construct__secret_mainnet_uncompressed__valid_expected11test_methodEv, __ZN13unicode_tests45unicode__to_utf8_main__null_termination__test11test_methodEv , __ZN13unicode_tests34unicode__to_utf8_main__ascii__test11test_methodEv , __ZN21stealth_address_tests52stealth_address__encoding__scan_mainnet__round_trips11test_methodEv , __ZN13unicode_tests34unicode__to_utf8_main__utf16__test11test_methodEv , __ZN21payment_address_tests52payment_address__version__script__valid_mainnet_p2sh11test_methodEv , __ZN19message_block_tests47block__factory_data_2__genesis_mainnet__success11test_methodEv , __ZN13satoshi_words21satoshi_words_mainnet11test_methodEv , __ZN19message_block_tests47block__factory_data_3__genesis_mainnet__success11test_methodEv , __ZN21payment_address_tests42payment_address__version__default__mainnet11test_methodEv , __ZN17chain_block_tests25block_serialization_tests40block__genesis__mainnet__valid_structure11test_methodEv , __ZN17chain_block_tests25block_serialization_tests42block__factory_3__genesis_mainnet__success11test_methodEv , __ZN14settings_tests46settings__construct__mainnet_context__expected11test_methodEv , __ZN19message_block_tests47block__factory_data_1__genesis_mainnet__success11test_methodEv , __ZN18chain_header_tests41header__proof1__genesis_mainnet__expected11test_methodEv , __ZN21stealth_address_tests56stealth_address__encoding__scan_pub_mainnet__round_trips11test_methodEv , __ZN17chain_block_tests25block_serialization_tests42block__factory_2__genesis_mainnet__success11test_methodEv , __ZN17chain_block_tests25block_serialization_tests42block__factory_1__genesis_mainnet__success11test_methodEv , __ZN18chain_header_tests41header__proof2__genesis_mainnet__expected11test_methodEv )
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [test/libbitcoin-test] Error 1
make: *** [check-am] Error 2
```

Succeeds when building without --disable-shared

```
 CXXLD    test/libbitcoin-test
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS
PASS: libbitcoin-test_runner.sh
============================================================================
Testsuite summary for libbitcoin 4.0.0
============================================================================
# TOTAL: 1
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Running 1936 test cases...
Platform: Mac OS
Compiler: Clang version 9.1.0 (clang-902.0.39.1)
STL     : libc++ version 5000
Boost   : 1.67.0

real	11m42.833s
user	23m10.153s
sys	6m4.837s
```

**Comment by evoskuil** [comment] 2018-08-12 01:03
See Travis build for clang/osx --disable_shared:
https://travis-ci.org/libbitcoin/libbitcoin/jobs/412854000#L436
and test result:
https://travis-ci.org/libbitcoin/libbitcoin/jobs/412854000#L1214
with boost  1.67.0
https://travis-ci.org/libbitcoin/libbitcoin/jobs/412854000#L1228

**Comment by JasonCoombs** [comment] 2018-08-12 01:37
Those Travis builds ended up being DISABLE_STATIC not DISABLE_SHARED

**Comment by JasonCoombs** [comment] 2018-08-12 01:50
something causes this instead of --disable-shared (and note also --enable-isystem is unknown):

`$ if [[ $OSX   && $CLANG && $DYNAMIC ]]; then CC=$CC CXX=$CXX ./install.sh --enable-isystem --disable-static; fi
`
https://travis-ci.org/libbitcoin/libbitcoin/jobs/414963493

**Comment by evoskuil** [comment] 2018-08-12 01:57
That just means I gave you the wrong link, there is one of each.

**Comment by evoskuil** [comment] 2018-08-12 01:58
@pmienk should isystem be parameterized for clang?

**Comment by JasonCoombs** [comment] 2018-08-12 01:59
got it. here's the DISABLE_SHARED build, with Boost 1.62:

https://travis-ci.org/libbitcoin/libbitcoin/jobs/414963494

**Comment by pmienk** [comment] 2018-08-12 02:06
--enable-isystem is unrelated.  That travis-ci logs include a warning when the parameter is passed to secp256k1.  It's correctly interpreted with clang.

**Comment by JasonCoombs** [comment] 2018-08-12 02:08
the build you referenced, above, with DISABLE_SHARED, ended up using boost 1.62 not 1.67 and I don't see where your 1.67 Travis build decided to use 1.67, it just looks like it used --build-boost

that's the only thing I see different right now between this Travis build and mine which fails:

https://travis-ci.org/libbitcoin/libbitcoin/jobs/412854001

**Comment by JasonCoombs** [comment] 2018-08-12 02:14
This line says use --disable-shared but the build command ignores it and uses --disable-static instead

https://travis-ci.org/libbitcoin/libbitcoin/jobs/412854000#L447

**Comment by JasonCoombs** [comment] 2018-08-12 19:05
I was able to reproduce the problem, and I still don't see any reason for it to fail. Boost is located just fine by configure, so why doesn't this succeed?

https://travis-ci.org/JasonCoombs/libbitcoin/builds/415096063

**Comment by JasonCoombs** [comment] 2018-08-12 19:11
There is no with_boost pointing to the location of the newly-built boost library if --build-boost is not specified, but shouldn't it be finding and linking the default lib? confused.

**Comment by evoskuil** [comment] 2018-08-12 19:17
We have installer CI runs where we build boost and where we do not, all of which work reliably. It’s hard to guess what is going on in your environment, but the build works in each scenario you are describing.

**Comment by JasonCoombs** [comment] 2018-08-12 20:08
Not sure about boost-test but I'm not referring to my environment. In this Travis build it's just a fork of libbitcoin with no changes other than to the .travis.yml

https://travis-ci.org/JasonCoombs/libbitcoin/jobs/415096064/config

By building with --disable-shared but without --build-boost it seems that Boost is not linked, and thus the error Undefined symbol "_main"

**Comment by JasonCoombs** [comment] 2018-08-12 20:14
But it's news to me that Boost provides a main function. Does Boost automatically insert its own main() function for a static build that isn't using the Unit Test Framework?

https://www.boost.org/doc/libs/1_61_0/libs/test/doc/html/boost_test/adv_scenarios/entry_point_overview.html

**Comment by evoskuil** [comment] 2018-08-12 20:43
Yes, based on macros.

**Comment by evoskuil** [comment] 2018-08-12 20:45
It's still your environment. It seems that boost is not installed as required.

**Comment by pmienk** [comment] 2018-08-12 21:04
I'd give odds that the issue is that boost installed by packages is necessarily providing shared libraries for linkage.  That coupled with detection preferring shared over static libs regardless of install parameters (automake or the compiler's resolution of -l provided libraries) would likely lead to the issue.  Again, it's an environment one and not one we will resolve.  I can't even remember if it impacted how we laid out the test matrix.

**Comment by JasonCoombs** [comment] 2018-08-12 23:46
I'll test again later, try to suggest the correct revision to the build files. What I hope for is a successful static build when not building boost, if boost is found >= 1.62 as expected.

This:
https://github.com/libbitcoin/libbitcoin/issues/1007#issue-349774881

And this:
https://travis-ci.org/JasonCoombs/libbitcoin/jobs/415096064/config

should both work, and it's probably easy to ensure that it does, so we can build --disable-shared with a --prefix and without --build-boost

**Comment by JasonCoombs** [comment] 2018-08-12 23:51
Maybe we would also like to have an option to build with shared boost lib rather than static linking, but to avoid using the dynamic libbitcoin libs ... more of an issue for v3 and v4 co-existing, which is a user support issue long-term but also important for my primary use case in which different builds must be able to co-exist.

**Comment by evoskuil** [comment] 2018-08-12 23:55
All permutations are available, just don’t expect all to be supported by an installet.

**Comment by evoskuil** [comment] 2018-08-25 16:04
Status?

**Comment by JasonCoombs** [comment] 2018-08-30 18:51
There is still an issue with building --disable-shared and without --build-boost ... I've improved my own install.sh and will check it in later for local re-build, and will see if I come up with the right solution for this --disable-shared at that point also.

**Comment by evoskuil** [comment] 2018-09-03 02:03
As described this isn’t a problem with the installer.

**Comment by evoskuil** [comment] 2018-09-03 02:04
This is the design of libtool, as it prioritized shared libs if available, regardless of whether we build them.

**Comment by evoskuil** [comment] 2018-09-08 22:50
I'm closing this as won't fix because it's the intended behavior when using autotools, but if you think you have an improvement please issue a PR.

**Closed by evoskuil** 2018-09-08 22:50 UTC
Labels: build, wontfix
