### ISSUE TITLE
Boost TLS incompatibility with OSX clang.

### ISSUE THREAD

**Issue by wlbentley** [libbitcoin/libbitcoin#733] opened 2017-03-26 05:45 UTC
Trying to install libbitcoin following [OS X instructions for homebrew](https://github.com/libbitcoin/libbitcoin#using-homebrew).

Installed Boost version is boost-1.63.0.

**.install.sh** fails with four boost errors. Final records of the output below. Complete Gist [here](https://gist.github.com/wlbentley/0fcc48526e3eae6d905f08438ce13ec9).

Any thoughts on how to resolve this and complete the installation?

Thanks once again.

=======================

In file included from /usr/local/include/boost/multiprecision/detail/default_ops.hpp:1605:
/usr/local/include/boost/multiprecision/detail/functions/constants.hpp:246:47: error: initializer
      for thread-local variable must be a constant expression
  ...long digits = boost::multiprecision::detail::digits2<number<T> >::value();
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/multiprecision/detail/functions/constants.hpp:246:38: note: use
      'thread_local' to allow this
   static BOOST_MP_THREAD_LOCAL long digits = boost::multiprecision::detail::digits2<number...
                                     ^
/usr/local/include/boost/multiprecision/detail/functions/constants.hpp:267:47: error: initializer
      for thread-local variable must be a constant expression
  ...long digits = boost::multiprecision::detail::digits2<number<T> >::value();
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/multiprecision/detail/functions/constants.hpp:267:38: note: use
      'thread_local' to allow this
   static BOOST_MP_THREAD_LOCAL long digits = boost::multiprecision::detail::digits2<number...
                                     ^
/usr/local/include/boost/multiprecision/detail/functions/constants.hpp:285:47: error: initializer
      for thread-local variable must be a constant expression
  ...long digits = boost::multiprecision::detail::digits2<number<T> >::value();
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/multiprecision/detail/functions/constants.hpp:285:38: note: use
      'thread_local' to allow this
   static BOOST_MP_THREAD_LOCAL long digits = boost::multiprecision::detail::digits2<number...
                                     ^
In file included from src/utility/random.cpp:28:
In file included from ./include/bitcoin/bitcoin/constants.hpp:25:
In file included from ./include/bitcoin/bitcoin/config/checkpoint.hpp:27:
In file included from ./include/bitcoin/bitcoin/formats/base_16.hpp:24:
In file included from ./include/bitcoin/bitcoin/math/hash.hpp:26:
In file included from /usr/local/include/boost/multiprecision/cpp_int.hpp:12:
In file included from /usr/local/include/boost/multiprecision/number.hpp:22:
In file included from /usr/local/include/boost/multiprecision/detail/generic_interconvert.hpp:9:
In file included from /usr/local/include/boost/multiprecision/detail/default_ops.hpp:1606:
/usr/local/include/boost/multiprecision/detail/functions/pow.hpp:384:47: error: initializer for
      thread-local variable must be a constant expression
  ...long digits = boost::multiprecision::detail::digits2<number<T> >::value();
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/multiprecision/detail/functions/pow.hpp:384:38: note: use 'thread_local'
      to allow this
   static BOOST_MP_THREAD_LOCAL long digits = boost::multiprecision::detail::digits2<number...
                                     ^
  CXX      src/utility/src_libbitcoin_la-thread.lo
  CXX      src/utility/src_libbitcoin_la-threadpool.lo
4 errors generated.
make: *** [src/utility/src_libbitcoin_la-random.lo] Error 1
make: *** Waiting for unfinished jobs....
$

**Comment by evoskuil** [comment] 2017-03-26 07:08
It's a boost bug, see [version 1.63 release notes](http://www.boost.org/users/history/version_1_63_0.html).
```
#11687 Xcode (Apple clang) and thread_local
```

> Xcode version 6+ does not ship with support for the keyword thread_local. According to [apple]( https://devforums.apple.com/thread/251372?tstart=0) they have no plans of supporting the keyword anytime soon. This leaves the library unusable on all Apple platforms.

https://svn.boost.org/trac/boost/ticket/11687

The resolution is set to wontfix (which I find quite surprising). I would +1 the bug with boost and downgrade the dependency. You can alternatively use the `--build-boost` option with `install.sh`. That also allows the installer to work around a boost-icu bug. Also, I generally recommend a `--prefix` install.

**Comment by evoskuil** [comment] 2017-03-26 07:34
Keeping this open for tracking. The specific boost bug is the same problem but it has been recently extended to `boost::multiprecision` (which we use) in [this commit](multiprecision).

**Comment by xmr-eric** [comment] 2017-05-08 21:54
So is there any solution to this for those of us with OSX who have Boost 1.64 installed?

**Comment by xmr-eric** [comment] 2017-05-08 21:54
I mean 1.63

**Comment by evoskuil** [comment] 2017-05-08 22:19
Yes, build in a prefix dir with a local version of boost. The installer provides both options.

**Comment by xmr-eric** [comment] 2017-05-08 23:21
I ran `./install.sh --build-boost` and it errored by saying: 

> cp: /usr/local/lib/libboost_chrono.a: Permission denied
> ...removing /usr/local/lib/libboost_chrono.a
> ...failed updating 1 target...

What are the correct steps?

**Comment by evoskuil** [comment] 2017-05-09 02:54
If you install without specifying a prefix directory it will default to /usr/local/ which generally requires elevated permissions (sudo). I recommend using a prefix directory. See the [bx readme](https://github.com/libbitcoin/libbitcoin-explorer/blob/master/README.md#build-notes-for-linux--macos) or [libbitcoin readme](https://github.com/libbitcoin/libbitcoin#build-notes-for-linux--macos) for installation instructions.

**Comment by jzmaddock** [comment] 2017-05-15 18:00
With apologies for just catching up on this issue.  If you define BOOST_NO_CXX11_THREAD_LOCAL when building/using Boost.Multiprecision then all use of the thread_local keyword will be suppressed and that should fix the issue.

Tracking back, this macro is set depending on whether clang returns true/false to __has_feature(cxx_thread_local) - so clang is advertising support for this but apparently it doesn't work - or at least is heavily crippled.  Or else I'm misunderstanding what's allowed here...

**Comment by evoskuil** [comment] 2017-05-16 01:48
Thanks @jzmaddock. Does this preclude the use of `boost::thread_specific_ptr<T>`?

**Comment by jzmaddock** [comment] 2017-05-16 11:07
On 16/05/2017 02:48, Eric Voskuil wrote:
>
> Thanks @jzmaddock <https://github.com/jzmaddock>. Does this preclude 
> the use of |boost::thread_specific_ptr<T>|?
>

It doesn't appear to use thread_local, so it should be unaffected so far 
as I can tell.

---
This email has been checked for viruses by AVG.
http://www.avg.com

**Comment by jzmaddock** [comment] 2017-05-20 17:09
Do we know which XCode versions are affected?  Trying to figure out a way to reproduce...

**Comment by evoskuil** [comment] 2017-05-20 19:24
In one of the related issues above this version of llbm/clang is reported, maybe that will help identify the necessary version of Xcode:

Apple LLVM version 8.1.0 (clang-802.0.38)

**Comment by jzmaddock** [comment] 2017-05-25 17:14
Here's what I've found about the various XCode versions, based on what our travis tests are reporting:

XCode | Clang | thread_local support?
-------|-------|-----------------------
6.4 | 6.1.0 (clang-602.0.53) | No
7.3 | 7.3.0 (clang-703.0.31) | No
8.0 | 7.3.0 (clang-703.0.31) | No
8.1 | 8.0.0 (clang-800.0.42.1) | Yes
8.2 | 8.0.0 (clang-800.0.42.1) | Yes
8.3 | 8.1.0 (clang-802.0.42) | Yes

So the OP is using clang-802.0.38, which appears to be XCode 8.3, but not quite the latest release?

Whatever, our tests are passing on travis with all their XCode installs including 8.3, so I'm perplexed.  I also note that there is no instantiation backtrace in the error log - which suggests the compiler is choking simply parsing the header?

Anyway I'm wondering if this is a temporary XCode glitch that's fixed by using the latest 8.3 version?

**Comment by evoskuil** [comment] 2017-05-26 08:04
@jzmaddock thanks for your work on this. I'm not set up well to test this at the moment. But I ran across [this code segment](https://github.com/libbitcoin/libbitcoin/blob/version3/include/bitcoin/bitcoin/utility/thread.hpp#L30-L41), which seems important. I've so far been unable to divine the reason the code was required at the time it was added. It may be dead code at this point. I've disabled it in our master branch (staging) and have had no build problems on any of our current platforms. Could you please take a look at see if this might explain it?

**Comment by jzmaddock** [comment] 2017-05-26 08:55
On 26/05/2017 09:04, Eric Voskuil wrote:
>
> @jzmaddock <https://github.com/jzmaddock> thanks for your work on 
> this. I'm not set up well to test this at the moment. But I ran across 
> this code segment 
> <https://github.com/libbitcoin/libbitcoin/blob/version3/include/bitcoin/bitcoin/utility/thread.hpp#L30-L41>, 
> which seems important. I've so far been unable to divine the reason 
> the code was required at the time it was added. It may be dead code at 
> this point. I've disabled it in our master branch (staging) and have 
> had no build problems on any of our current platforms. Could you 
> please take a look at see if this might explain it?
>

That would cause it!  You redefine the thread_local keyword to __thread, 
and __thread has limitations that thread_local does not.

John.

---
This email has been checked for viruses by AVG.
http://www.avg.com

**Comment by evoskuil** [comment] 2017-05-27 09:10
Thanks! I'll see if we can backport this to production code and get it retested on the problem platforms.

**Comment by sugarjig** [comment] 2017-08-11 00:16
Has this issue been resolved? I'm seeing the same errors when trying to build.

clang version: `Apple LLVM version 8.1.0 (clang-802.0.42)`
boost version: `1.64.0`

**Comment by evoskuil** [comment] 2017-08-11 05:39
@sugarjig Version3 branch? It appears I dropped the ball on this and didn't get it backported. Doing it now.

**Comment by sugarjig** [comment] 2017-08-11 13:47
Thanks for getting that in!

I was trying to build version 3.2.0 of libbitcoin, so I guess not quite the tip of version3. Any idea when a new release will come out with these changes? (My goal is to make a Homebrew formula, so I'm sticking with release builds)

**Comment by evoskuil** [comment] 2017-08-11 17:38
I will tag v3.3.0 in the next day or so.

**Comment by sugarjig** [comment] 2017-08-16 01:54
Works for me now! I was able to create a working Homebrew formula. The [pull request](https://github.com/Homebrew/homebrew-core/pull/16771) is waiting for approval. Hopefully very soon, installing `libbitcoin` will be as easy as `brew install libbitcoin`. Thanks for you help!

**Comment by evoskuil** [comment] 2017-08-16 05:09
Nice!!

**Closed by evoskuil** 2017-08-16 05:09 UTC
Labels: build
